name: tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .[jax_cpu]
        pip install .[pytorch_cpu]
        pip install .[wmt]
        pip install .[ogbg]
        pip install .[criteo1tb]
    - name: Run pytest
      run: |
        pytest -vx tests/version_test.py
        pytest -vx tests/test_num_params.py
        pytest -vx tests/test_param_shapes.py
        pytest -vx tests/test_param_types.py
        pytest -vx tests/test_ssim.py
    - name: Run criteo1tb jax test
      run: |
        python3 tests/reference_algorithm_tests.py --workload=criteo1tb     --framework=jax     --global_batch_size=16     --submission_path=reference_algorithms/target_setting_algorithms/jax_adamw.py     --tuning_search_space=reference_algorithms/target_setting_algorithms/criteo1tb/tuning_search_space.json
        
